<?php namespace backend\controllers;

use common\components\rbac\PermissionsHelper;
use common\controllers\BaseController;

class BackendController extends BaseController
{
    public function beforeAction($action)
    {
        $this->loginControllerName = LoginController::CONTROLLER_NAME;
        $this->loginUrl = LoginController::LOGIN_URL;
        $this->moduleName = PermissionsHelper::ADMIN;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
