<?php namespace frontend\controllers;

use common\controllers\BaseController;

class FrontendController extends BaseController
{
    public function beforeAction($action)
    {
        $this->loginUrl = "/signup";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
